version: '2'
services:
  avid-app:
    image: avid
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:avid;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
